---
  - hosts: all
    gather_facts: false
    become: true
    vars:
      default_venv_path: /var/lib/awx/venv/ansible
      venv_path: /var/lib/awx/venv/custom_env
      nexus_host: sonatype-nexus-host.co.uk
      nexus_repo: Python-Modules-From-Source
      nexus_url: "https://{{ nexus_host }}/nexus/service/local/repositories/{{ nexus_repo }}/content/pypi"
      pip_modules:
        - { name: 'httplib2', version: '0.13.1' }
        - { name: 'pyasn1', version: '0.4.7' }
        - { name: 'pyasn1-modules', version: '0.2.6' }
        - { name: 'rsa', version: '4.0' }
        - { name: 'six', version: '1.12.0' }
        - { name: 'cachetools', version: '3.1.1' }
        - { name: 'google-auth', version: '1.6.3' }
        - { name: 'oauth2client', version: '4.1.3' }
        - { name: 'google-auth-httplib2', version: '0.0.3' }
        - { name: 'urllib3', version: '1.25.3' }
        - { name: 'uritemplate', version: '3.0.0' }
        - { name: 'google-api-python-client', version: '1.7.11' }
    tasks:
     - name: Install PIP Modules in custom venv
       pip:
        name: "{{ nexus_url }}/{{ item.name }}/{{ item.version }}/{{ item.name }}-{{ item.version }}.tgz"
        extra_args: "--trusted-host {{ nexus_host }}"
        virtualenv: "{{ venv_path }}"
        virtualenv_site_packages: yes
       with_items: "{{ pip_modules }}"

     - name: Install PIP Modules in standard venv
       pip:
        name: "{{ nexus_url }}/{{ item.name }}/{{ item.version }}/{{ item.name }}-{{ item.version }}.tgz"
        extra_args: "--trusted-host {{ nexus_host }}"
        virtualenv: "{{ default_venv_path }}"
        virtualenv_site_packages: yes
       with_items: "{{ pip_modules }}"

     - name: Ensure all standard modules are present in venv
       shell: "cp -r {{ default_venv_path }}/lib/python2.7/site-packages/. {{ venv_path }}/lib/python2.7/site-packages/"

     - name: Run Ansible galaxy
       shell: ansible-galaxy collection install theforeman.foreman
       environment:
         http_proxy: http://1.1.2.3:80
         https_proxy: http://1.1.2.3:80
